In [2]:
import numpy as np

In [3]:
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
a.shape
(3, 5)

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype.name

'int32'

In [7]:
a.itemsize

4

In [8]:
a.size

20

In [9]:
type(a)

numpy.ndarray

In [10]:
a = np.indices((3,3))
a

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [12]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [14]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
a = np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [16]:
rep = np.repeat("2020",2)
rep

array(['2020', '2020'], dtype='<U4')

In [18]:
a=np.empty( (2,1) ) 
a

array([[1.01855798e-312],
       [1.01855798e-312]])

In [31]:
b = np.arange(12).reshape(3,4)
b.sum(axis=0)

array([12, 15, 18, 21])

In [32]:
b.min(axis=1)

array([0, 4, 8])

In [33]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [37]:
B = np.arange(5)
np.exp(B)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [38]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [40]:
np.all([[True,True],[True,True]])

True

In [41]:
np.any([[True, False], [True, True]])

True

In [44]:
x = np.arange(4).reshape((2,2))
x
np.transpose(x)

array([[0, 2],
       [1, 3]])

In [49]:
a = np.arange(8).reshape((2,2,2))
a
np.trace(a)

array([6, 8])

In [50]:
np.sum([[0, 3], [0, 6]])

9

In [52]:
np.sum([[0, 1], [0, 4]], axis=1)

array([1, 4])

In [57]:
a = np.array([[1, 2], [3, 2]])
np.std(a)

0.7071067811865476

In [61]:
a = np.array([[4,2],[5,1],[3,2]])
np.sort(a)

array([[2, 4],
       [1, 5],
       [2, 3]])

In [62]:
x = np.array([536870910, 536870910, 536870910, 536870910])
np.prod(x)

16

In [64]:
np.minimum([9, 8, 1], [1, 5, 2])

array([1, 5, 1])

In [65]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.median(a)

3.5

In [67]:
a = np.array([[1, 2], [3, 6]])
np.mean(a)

3.0

In [70]:
np.maximum([2, 3, 2], [1, 6, 2])

array([2, 6, 2])

In [71]:
x = np.invert(np.array(13, dtype=np.uint8))
x

242

In [72]:
np.binary_repr(x, width=8)

'11110010'

In [73]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

In [77]:
np.dot(-2, 2)

-4

In [79]:
data = np.arange(1, 7)
np.average(data)

3.5

In [80]:
a = np.arange(6).reshape(2,3) + 10
a
np.argmax(a)

5

In [82]:
x = np.random.randint(10)
x

3

In [84]:
a = np.random.randint(2,8,size=9)
a

array([2, 6, 6, 4, 4, 3, 5, 7, 6])

In [85]:
a = np.random.ranf(5)
a

array([0.59450278, 0.8197639 , 0.50575471, 0.41850855, 0.68739076])

In [88]:
(np.char.add(['Num', 'Assign'],['py', 'ment']))

array(['Numpy', 'Assignment'], dtype='<U10')

In [89]:
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)
x

array([ 90., 180., 270., 360.])

In [91]:
base = 1
perp = 2
x = np.hypot(base, perp)
x

2.23606797749979

In [95]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [97]:
np.full((2, 2), 20)

array([[20, 20],
       [20, 20]])

In [98]:
a = np.array([[30,40,0],[0,20,10],[50,0,60]]) 
np.nonzero (a)

(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 1, 2, 0, 2], dtype=int64))

In [100]:
a = np.random.beta(1,4)
a

0.2137319257591706

In [101]:
a = np.random.chisquare(2,6)
a

array([2.21044004, 1.32265989, 2.11216873, 0.58182182, 1.64429128,
       2.15637187])

In [104]:
a = np.random.dirichlet((2, 2, 3),4).transpose()
a

array([[0.07683613, 0.38839562, 0.43859122, 0.37968906],
       [0.52438714, 0.37758073, 0.0387924 , 0.18949405],
       [0.39877673, 0.23402366, 0.52261637, 0.43081689]])